#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap/app.php';
//require_once __DIR__ . '/vendor/autoload.php';

use App\Console\Kernel;

$kernel = new Kernel();
$kernel->handle($argv);

//$console = new Kernel();
//$console->addCommand(new TestCommand());
//$console->run();
